import random

carros = [
    "Chevrolet Agile",
    "Chevrolet C-10",
    "Chevrolet Camaro",
    "Chevrolet Caravan",
    "Chevrolet Celta",
    "Chevrolet Chevette",
    "Chevrolet Corsa",
    "Chevrolet Covalt",
    "Chevrolet D-20",
    "Chevrolet Monza",
    "Chevrolet Onix",
    "Chevrolet Opala",
    "Chevrolet Veraneio",
    "Citroën C3",
    "Fiat 147",
    "Fiat Argo",
    "Fiat Cronos",
    "Fiat Mobi",
    "Fiat Panorama",
    "Ford Corcel",
    "Ford Escort",
    "Ford F-1000",
    "Ford Ka",
    "Ford Maverick",
    "Honda City",
    "Honda Fit",
    "Hyundai Azera",
    "Hyundai HB20",
    "Hyundai IX-35",
    "Hyundai Veloster",
    "Peugeot 2008",
    "Peugeot 206",
    "Peugeot 208",
    "Peugeot 3008",
    "Peugeot 306",
    "Peugeot 308",
    "Renault Kwid",
    "Renault Logan",
    "Renault Sandero",
    "Renault Twingo",
    "Renault Zoe",
    "Toyota Etios",
    "Toyota Yaris ",
    "Volkswagen Apolo",
    "Volkswagen Bora",
    "Volkswagen Brasilia",
    "Volkswagen Fusca",
    "Volkswagen Gol",
    "Volkswagen Kombi",
    "Volkswagen Parati",
    "Volkswagen Passat",
    "Volkswagen Polo",
    "Volkswagen SP2",
    "Volkswagen Santana",
    "Volkswagen Voyage",
    "Volkswagen up!",
]

random_carros = random.choice(carros)

print("Você deve dirigir um " + random_carros)
