FROM python:3.8-slim-buster

COPY carguru.py /app/carguru.py

WORKDIR /app

CMD ["python", "carguru.py"]

# cria a imagem:
# docker build -t carguru-app .

# executa o container:
# docker run carguru-app
